declare module 'electron-compile';
declare module 'electron-debug';
declare module 'electron-devtools-installer';
declare module 'electron-devtools-installer';
declare module 'electron-remote';
declare module 'dotenv';
declare module 'lodash.pick';
declare module 'material-ui/*';
declare module 'react-virtualized';